### ISSUE TITLE
Error on running SizerNet and ParserNet evaluation scripts

### ISSUE THREAD

**Issue by aapatre** [garvita-tiwari/sizer#3]
Running the given evaluations scripts `python trainer/parsernet_eval.py --log_dir results -` and `python trainer/sizernet_eval.py --log_dir results -` gives the following error:

```
Traceback (most recent call last):
  File "trainer/parsernet_eval.py", line 3, in <module>
    import tensorboardX
  File "/home/ingnious/miniconda2/envs/py36/lib/python3.6/site-packages/tensorboardX/__init__.py", line 5, in <module>
    from .torchvis import TorchVis
  File "/home/ingnious/miniconda2/envs/py36/lib/python3.6/site-packages/tensorboardX/torchvis.py", line 11, in <module>
    from .writer import SummaryWriter
  File "/home/ingnious/miniconda2/envs/py36/lib/python3.6/site-packages/tensorboardX/writer.py", line 16, in <module>
    from .event_file_writer import EventFileWriter
  File "/home/ingnious/miniconda2/envs/py36/lib/python3.6/site-packages/tensorboardX/event_file_writer.py", line 28, in <module>
    from .proto import event_pb2
  File "/home/ingnious/miniconda2/envs/py36/lib/python3.6/site-packages/tensorboardX/proto/event_pb2.py", line 16, in <module>
    from tensorboardX.proto import summary_pb2 as tensorboardX_dot_proto_dot_summary__pb2
  File "/home/ingnious/miniconda2/envs/py36/lib/python3.6/site-packages/tensorboardX/proto/summary_pb2.py", line 16, in <module>
    from tensorboardX.proto import tensor_pb2 as tensorboardX_dot_proto_dot_tensor__pb2
  File "/home/ingnious/miniconda2/envs/py36/lib/python3.6/site-packages/tensorboardX/proto/tensor_pb2.py", line 16, in <module>
    from tensorboardX.proto import resource_handle_pb2 as tensorboardX_dot_proto_dot_resource__handle__pb2
  File "/home/ingnious/miniconda2/envs/py36/lib/python3.6/site-packages/tensorboardX/proto/resource_handle_pb2.py", line 23, in <module>
    serialized_pb=_b('\n(tensorboardX/proto/resource_handle.proto\x12\x0ctensorboardX\"r\n\x13ResourceHandleProto\x12\x0e\n\x06\x64\x65vice\x18\x01 \x01(\t\x12\x11\n\tcontainer\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x11\n\thash_code\x18\x04 \x01(\x04\x12\x17\n\x0fmaybe_type_name\x18\x05 \x01(\tB/\n\x18org.tensorflow.frameworkB\x0eResourceHandleP\x01\xf8\x01\x01\x62\x06proto3')
TypeError: __new__() got an unexpected keyword argument 'serialized_options'

```

**Comment by aapatre** [comment]
Ok, I used  `conda install -c conda-forge tensorboardx ` but then uninstalled it and reinstalled tensorboardX with pip and fixed the error:
`pip install tensorboardX`
